[project]
name = "traceml"
version = "0.0.1"
description = "TraceML: Lightweight ML Profiler"
authors = [{ name = "Abhinav Srivastav", email = "abhinavsriva@gmail.com" }]
readme = "README.md"
license = { text = "MIT License" }
requires-python = ">=3.9"


# Runtime dependencies
dependencies = [
    "rich>=13.7.0,<15.0.0",
    "psutil>=5.9.5,<6.0.0",
    "pynvml>=11.5.0,<12.0.0",
    "torch>=2.2.0",
    "scikit-learn>=1.3.0,<1.4.0",
    "numpy>=1.24.4,<1.26.0",
    "pandas>=2.0.3",
    "nvidia-ml-py3==7.352.0",
    "pytest>=8.4.1",
    "coverage>=7.10.5",
    "pytest-cov>=6.2.1"
]

[project.optional-dependencies]
dev = [
    "black>=24.1.0,<25.0.0",
    "flake8>=6.1.0,<7.0.0",
    "pytest>=7.0.0,<8.0.0"
]

[project.scripts]
traceml = "traceml.cli:main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
